version: "3"
services:
  fastapi:
    build: .
    environment:
      - OXIGRAPH_URL=http://oxigraph:7878
    ports: 
      - 8080:80
  oxigraph:
    image: ghcr.io/oxigraph/oxigraph:latest
    volumes:
      - ./data:/data
    ports:
      - 7878:7878
